-- Virtual news stories generated by the bots process.
--
-- sentiment/impact are the inputs the bot price model used, kept for analysis.
-- They are deliberately excluded from the public API response and the realtime
-- payload so the UI cannot reveal a story's direction or magnitude.
CREATE TABLE "market"."news_items" (
  "id" TEXT NOT NULL,
  "external_id" TEXT NOT NULL,
  "symbol" TEXT,
  "category" TEXT NOT NULL,
  "headline" TEXT NOT NULL,
  "body" TEXT,
  "sentiment" TEXT NOT NULL,
  "impact" INTEGER NOT NULL,
  "price_at_publish" INTEGER,
  "parent_external_id" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "news_items_pkey" PRIMARY KEY ("id")
);

-- The bots process may retry a publish; the external id keeps that idempotent.
CREATE UNIQUE INDEX "news_items_external_id_key" ON "market"."news_items" ("external_id");

-- The news tab reads newest-first across all symbols.
CREATE INDEX "news_items_created_at_idx" ON "market"."news_items" ("created_at");

-- The symbol panel reads one symbol's stories plus the market-wide ones.
CREATE INDEX "news_items_symbol_created_at_idx" ON "market"."news_items" ("symbol", "created_at");
