packages:
  - "apps/*"
  - "packages/*"
overrides:
  sharp: 0.35.4
  multer: 2.3.0
  nanoid: 3.3.18
  postcss: 8.5.23
  socket.io-parser: 4.2.7
  qs: 6.16.0
  deepmerge-ts: 8.0.0
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
