import type { ReplayDataset } from "./replay.types";

/**
 * These instruments live only in the replay lab. They never enter
 * market.symbols, the Redis order book, matching.trades, or settlement.
 */
export const REPLAY_DATASETS: readonly ReplayDataset[] = [
  {
    id: "aapl-us",
    symbol: "AAPL",
    name: "Apple Inc.",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "msft-us",
    symbol: "MSFT",
    name: "Microsoft Corporation",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "nvda-us",
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "amzn-us",
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "googl-us",
    symbol: "GOOGL",
    name: "Alphabet Inc. Class A",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "meta-us",
    symbol: "META",
    name: "Meta Platforms, Inc.",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "tsla-us",
    symbol: "TSLA",
    name: "Tesla, Inc.",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "amd-us",
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc.",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "nflx-us",
    symbol: "NFLX",
    name: "Netflix, Inc.",
    category: "overseas",
    exchange: "NASDAQ",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "jpm-us",
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    category: "overseas",
    exchange: "NYSE",
    currency: "USD",
    priceScale: 100,
  },
  {
    id: "samsung-electronics-kr",
    symbol: "005930",
    name: "삼성전자",
    category: "domestic",
    exchange: "KOSPI",
    currency: "KRW",
    priceScale: 1,
  },
  {
    id: "sk-hynix-kr",
    symbol: "000660",
    name: "SK하이닉스",
    category: "domestic",
    exchange: "KOSPI",
    currency: "KRW",
    priceScale: 1,
  },
  {
    id: "hyundai-motor-kr",
    symbol: "005380",
    name: "현대차",
    category: "domestic",
    exchange: "KOSPI",
    currency: "KRW",
    priceScale: 1,
  },
  {
    id: "naver-kr",
    symbol: "035420",
    name: "NAVER",
    category: "domestic",
    exchange: "KOSPI",
    currency: "KRW",
    priceScale: 1,
  },
  {
    id: "posco-holdings-kr",
    symbol: "005490",
    name: "POSCO홀딩스",
    category: "domestic",
    exchange: "KOSPI",
    currency: "KRW",
    priceScale: 1,
  },
  {
    id: "btc-usd",
    symbol: "BTC/USD",
    name: "Bitcoin",
    category: "crypto",
    exchange: "CRYPTO",
    currency: "USD",
    priceScale: 100,
  },
];

export function findReplayDataset(id: string): ReplayDataset | undefined {
  return REPLAY_DATASETS.find((dataset) => dataset.id === id);
}
