import type { NewsTemplate } from "../types";

/** 사업·성장 — 수주, 신제품, 증설, M&A, 신용등급, 인허가 */
export const BUSINESS_TEMPLATES: readonly NewsTemplate[] = [
  {
    id: "biz.order",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.45, max: 0.72 },
    headlines: [
      "{name}, {country} {counterparty}{과} {money} 규모 {product} 공급계약",
      "{name}, {country}서 {money} 규모 {product} 수주",
    ],
    body: ["계약 기간은 {duration}이며 연간 매출에 순차 반영된다."],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      counterparty: { kind: "pick", vocab: "counterparty" },
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.03, max: 0.22 } },
      duration: { kind: "duration", range: { min: 2, max: 6 }, unit: "년" },
    },
    followUp: {
      chance: 0.55,
      delayMs: { min: 240_000, max: 660_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.order.contract", polarity: "SAME", strengthScale: 0.55 },
        { probability: 0.3, templateId: "seq.order.delay", polarity: "REVERSE", strengthScale: 0.45 },
        { probability: 0.2, templateId: "seq.order.cancel", polarity: "REVERSE", strengthScale: 0.9 },
      ],
    },
  },
  {
    id: "biz.order.mega",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.68, max: 0.9 },
    headlines: ["{name}, 창사 이래 최대 {money} 규모 {product} 수주"],
    body: ["{country} {counterparty}{과} 체결했으며 수주잔고가 크게 늘었다."],
    excludeSectors: ["BROKER", "REIT"],
    volumeMultiplier: { min: 1.5, max: 1.9 },
    slots: {
      country: { kind: "pick", vocab: "country" },
      counterparty: { kind: "pick", vocab: "counterparty" },
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.2, max: 0.45 } },
    },
    followUp: {
      chance: 0.65,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.55, templateId: "seq.order.contract", polarity: "SAME", strengthScale: 0.5 },
        { probability: 0.25, templateId: "seq.order.delay", polarity: "REVERSE", strengthScale: 0.45 },
        { probability: 0.2, templateId: "seq.order.cancel", polarity: "REVERSE", strengthScale: 0.85 },
      ],
    },
  },
  {
    id: "biz.order.cancel",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.55, max: 0.8 },
    headlines: ["{name}, {money} 규모 {product} 계약 해지 통보받아"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.05, max: 0.2 } },
    },
  },
  {
    id: "biz.product",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{name}, 차세대 {product} 공개… 내년 {quarter} 양산 목표"],
    excludeSectors: ["BROKER", "TRADING", "REIT"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      quarter: { kind: "quarter", offsetQuarters: 2 },
    },
  },
  {
    id: "biz.tech",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.48, max: 0.7 },
    headlines: ["{name}, {product} 개발 성공… 업계 최초 양산 체제 구축"],
    excludeSectors: ["BROKER", "TRADING", "REIT"],
    slots: { product: { kind: "pick", vocab: "product" } },
  },
  {
    // The growth story a financial firm actually gets: a licence, not a factory.
    id: "biz.license",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.4, max: 0.62 },
    headlines: [
      "{name}, {product} 본인가 획득… {quarter} 중 서비스 개시",
      "{agency}, {name} {product} 신규 인가… 수익 다변화 기대",
    ],
    sectors: ["BROKER"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      agency: { kind: "pick", vocab: "agency" },
      quarter: { kind: "quarter", offsetQuarters: 1 },
    },
  },
  {
    // Trading houses grow by securing rights and routes, not production lines.
    id: "biz.concession",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.42, max: 0.65 },
    headlines: ["{name}, {country} {product} 사업권 확보… {duration} 장기 계약"],
    sectors: ["TRADING"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      product: { kind: "pick", vocab: "product" },
      duration: { kind: "duration", range: { min: 5, max: 20 }, unit: "년" },
    },
  },
  {
    id: "biz.patent",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.25, max: 0.42 },
    headlines: ["{name}, {country}서 {product} 핵심 특허 {count} 등록"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      product: { kind: "pick", vocab: "product" },
      count: { kind: "count", range: { min: 3, max: 40 }, unit: "건" },
    },
  },
  {
    id: "biz.capex",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.55 },
    headlines: ["{name}, {plant}에 {money} 투자… {product} 공급능력 {pct} 확대"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      plant: { kind: "pick", vocab: "plant" },
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.1, max: 0.35 } },
      pct: { kind: "percent", range: { min: 20, max: 80 }, decimals: 0 },
    },
  },
  {
    id: "biz.ma.buy",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.42, max: 0.65 },
    headlines: ["{name}, {counterparty} 지분 {pct}{를} {money}에 인수"],
    slots: {
      counterparty: { kind: "pick", vocab: "counterparty" },
      pct: { kind: "percent", range: { min: 20, max: 100 }, decimals: 0 },
      money: { kind: "money", capFraction: { min: 0.05, max: 0.3 } },
    },
  },
  {
    id: "biz.ma.target",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.65, max: 0.9 },
    headlines: [
      "{name} 경영권 매각설… {counterparty} 인수 검토",
      "{name}, {inst} 주도 컨소시엄과 매각 협상설",
    ],
    volumeMultiplier: { min: 1.5, max: 2 },
    slots: {
      counterparty: { kind: "pick", vocab: "counterparty" },
      inst: { kind: "pick", vocab: "inst" },
    },
    followUp: {
      chance: 0.9,
      delayMs: { min: 120_000, max: 420_000 },
      outcomes: [
        { probability: 0.45, templateId: "seq.ma.confirm", polarity: "SAME", strengthScale: 0.6 },
        { probability: 0.55, templateId: "seq.ma.deny", polarity: "REVERSE", strengthScale: 0.85 },
      ],
    },
  },
  {
    id: "biz.spinoff.ipo",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.6 },
    headlines: ["{name}, 핵심 자회사 분할 상장 추진… 주주가치 훼손 우려"],
  },
  {
    id: "biz.stake.sale",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.32, max: 0.5 },
    headlines: ["{name}, 보유 {counterparty} 지분 {money}에 매각… 처분이익 {money2}"],
    slots: {
      counterparty: { kind: "pick", vocab: "counterparty" },
      money: { kind: "money", capFraction: { min: 0.03, max: 0.12 } },
      money2: { kind: "money", capFraction: { min: 0.01, max: 0.05 } },
    },
  },
  {
    id: "biz.credit.up",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.28, max: 0.45 },
    headlines: ["{rating}, {name} 신용등급 {grade}로 상향… 등급전망 '안정적'"],
    slots: {
      rating: { kind: "pick", vocab: "rating" },
      grade: { kind: "pick", vocab: "grade" },
    },
  },
  {
    id: "biz.credit.down",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.42, max: 0.62 },
    headlines: ["{rating}, {name} 신용등급 {grade}로 하향… 등급전망 '부정적'"],
    slots: {
      rating: { kind: "pick", vocab: "rating" },
      grade: { kind: "pick", vocab: "grade" },
    },
  },
  {
    id: "biz.approval",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.4, max: 0.62 },
    headlines: ["{name} {product}, {certifier} 인증 획득… {country} 수출길 열려"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      certifier: { kind: "pick", vocab: "certifier" },
      country: { kind: "pick", vocab: "country" },
    },
  },
  {
    id: "biz.approval.reject",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.45, max: 0.68 },
    headlines: ["{name} {product}, {certifier} 승인 보류… 상용화 {duration} 지연"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      certifier: { kind: "pick", vocab: "certifier" },
      duration: { kind: "duration", range: { min: 6, max: 24 }, unit: "개월" },
    },
  },
  // Written now, gated off until a pharma listing exists in SYMBOLS.
  {
    id: "bio.trial.success",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.7, max: 0.92 },
    headlines: ["{name}, {product} 임상 3상 1차 지표 충족"],
    sectors: ["BIO"],
    slots: { product: { kind: "pick", vocab: "product" } },
  },
  {
    id: "bio.trial.fail",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.75, max: 0.95 },
    headlines: ["{name}, {product} 임상 3상 실패… 개발 중단"],
    sectors: ["BIO"],
    slots: { product: { kind: "pick", vocab: "product" } },
  },

  {
    id: "biz.plant.open",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name}, {plant} 신공장 준공… 생산능력 {pct} 확대", "{name} {plant} 증설 라인 가동 개시"],
    body: ["총 {money}가 투입됐으며 내년부터 매출에 기여할 전망이다."],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      plant: { kind: "pick", vocab: "plant" },
      pct: { kind: "percent", range: { min: 15, max: 45 }, decimals: 0 },
      money: { kind: "money", capFraction: { min: 0.04, max: 0.18 } },
    },
  },
  {
    id: "biz.subsidy",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["정부, {name} {product} 사업에 {money} 보조금 확정", "{name}, {country} 정부 인센티브 {money} 확보"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      country: { kind: "pick", vocab: "country" },
      money: { kind: "money", capFraction: { min: 0.02, max: 0.1 } },
    },
  },
  {
    id: "biz.partnership",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{name}, {country} {counterparty}{과} {product} 공동개발 MOU", "{name}·{counterparty}, {product} 전략적 제휴"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      counterparty: { kind: "pick", vocab: "counterparty" },
      product: { kind: "pick", vocab: "product" },
    },
  },
  {
    id: "biz.export.record",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.32, max: 0.52 },
    headlines: ["{name}, {product} 월간 수출 {money}… 사상 최대", "{name} {product} 해외 매출 비중 {pct} 돌파"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.01, max: 0.05 } },
      pct: { kind: "percent", range: { min: 40, max: 75 }, decimals: 0 },
    },
  },
  {
    id: "biz.esg.up",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.2, max: 0.35 },
    headlines: ["{name}, ESG 평가 {grade} 등급… 통합등급 상향"],
    slots: { grade: { kind: "pick", vocab: "grade" } },
  },
  {
    id: "biz.contract.lost",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name}, {country} {product} 입찰서 고배… 경쟁사에 밀려", "{name}, {money} 규모 {product} 수주 경쟁서 탈락"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.05, max: 0.2 } },
    },
  },
];
