import type { NewsTemplate } from "../types";

/**
 * 업종별 회사 뉴스 — 업종마다 실제 시장에서 자주 나오는 종류의 기사. `sectors`로 그 업종
 * 회사에만 나가게 해, 리츠가 신차를 내거나 전력사가 판호를 받는 일이 없게 한다.
 * 맨 아래는 업종과 무관하게 어느 회사에나 나올 수 있는 지배구조·수급 기사다.
 */
export const INDUSTRY_COMPANY_TEMPLATES: readonly NewsTemplate[] = [
  // ── 자동차 ─────────────────────────────────────────────────
  {
    id: "co.auto.sales.record",
    category: "EARNINGS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name}, {quarter} 글로벌 판매 {count} 기록… 분기 최대"],
    sectors: ["AUTO"],
    slots: {
      quarter: { kind: "quarter" },
      count: { kind: "count", range: { min: 900_000, max: 1_200_000 }, unit: "대" },
    },
  },
  {
    id: "co.auto.newcar.hit",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name} 신형 {product}, 사전계약 {count} 돌파"],
    sectors: ["AUTO"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      count: { kind: "count", range: { min: 20_000, max: 80_000 }, unit: "대" },
    },
  },
  {
    id: "co.auto.recall.engine",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name}, {country}서 {count} 리콜… 충당금 {money} 반영 전망"],
    sectors: ["AUTO"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      count: { kind: "count", range: { min: 80_000, max: 600_000 }, unit: "대" },
      money: { kind: "money", capFraction: { min: 0.02, max: 0.08 } },
    },
    followUp: {
      chance: 0.7,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.45, templateId: "seq.recall.expand", polarity: "SAME", strengthScale: 0.8 },
        { probability: 0.55, templateId: "seq.recall.close", polarity: "REVERSE", strengthScale: 0.6 },
      ],
    },
  },

  // ── 에너지·유틸리티 ─────────────────────────────────────────
  {
    id: "co.energy.margin",
    category: "EARNINGS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name}, 고도화 설비 가동률 {pct}… {quarter} 정유 부문 흑자 전망"],
    sectors: ["ENERGY"],
    slots: {
      pct: { kind: "percent", range: { min: 92, max: 99 } },
      quarter: { kind: "quarter", offsetQuarters: 0 },
    },
  },
  {
    id: "co.energy.shutdown",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name} {plant} 정유공장 정기보수 연장… {duration} 가동 중단"],
    sectors: ["ENERGY"],
    slots: {
      plant: { kind: "pick", vocab: "plant" },
      duration: { kind: "duration", range: { min: 20, max: 45 }, unit: "일" },
    },
  },
  {
    id: "co.utility.turnaround",
    category: "EARNINGS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.38, max: 0.62 },
    headlines: ["{name}, 요금 인상 효과로 {quarter} 흑자 전환 전망"],
    sectors: ["UTILITY"],
    slots: { quarter: { kind: "quarter", offsetQuarters: 0 } },
  },
  {
    id: "co.utility.fuel.cost",
    category: "EARNINGS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name}, LNG 도입 단가 {pct} 상승… 연료비 부담 확대"],
    sectors: ["UTILITY"],
    slots: { pct: { kind: "percent", range: { min: 8, max: 25 } } },
  },
  {
    id: "co.utility.dividend",
    category: "CAPITAL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{name}, {count} 만에 배당 재개… 주당 {level} 결정"],
    sectors: ["UTILITY"],
    slots: {
      count: { kind: "count", range: { min: 2, max: 4 }, unit: "년" },
      level: { kind: "level", range: { min: 200, max: 600 }, unit: "원" },
    },
  },

  // ── 리츠 ───────────────────────────────────────────────────
  {
    id: "co.reit.asset.buy",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name}, {money} 규모 {product} 편입… 배당 수익률 상향"],
    sectors: ["REIT"],
    slots: {
      money: { kind: "money", capFraction: { min: 0.1, max: 0.35 } },
      product: { kind: "pick", vocab: "product" },
    },
  },
  {
    id: "co.reit.asset.sale",
    category: "CAPITAL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name}, 보유 자산 매각 차익 {money}… 특별배당 검토"],
    sectors: ["REIT"],
    slots: { money: { kind: "money", capFraction: { min: 0.03, max: 0.1 } } },
  },
  {
    id: "co.reit.vacancy",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name} {plant} 핵심 자산 임차인 이탈… 공실률 {pct}로 상승"],
    sectors: ["REIT"],
    slots: {
      plant: { kind: "pick", vocab: "plant" },
      pct: { kind: "percent", range: { min: 8, max: 20 } },
    },
  },
  {
    id: "co.reit.refinance",
    category: "CAPITAL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.33, max: 0.55 },
    headlines: ["{name}, 차입금 리파이낸싱 금리 {pct}p 상승… 배당 축소 우려"],
    sectors: ["REIT"],
    slots: { pct: { kind: "percent", range: { min: 0.8, max: 2 } } },
  },

  // ── 바이오 ─────────────────────────────────────────────────
  {
    id: "co.bio.license.out",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.6, max: 0.88 },
    headlines: ["{name}, {country} 제약사에 {product} 기술수출… 총 {money} 규모"],
    body: ["계약금은 전체의 일부이며 나머지는 임상·허가 단계별로 받는다."],
    sectors: ["BIO"],
    volumeMultiplier: { min: 1.5, max: 2 },
    slots: {
      country: { kind: "pick", vocab: "country" },
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.3, max: 1.2 } },
    },
  },
  {
    id: "co.bio.clinical.hold",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.55, max: 0.82 },
    headlines: ["{name} {product} 임상, {country} 규제당국 일시 중단 명령"],
    sectors: ["BIO"],
    followUp: {
      chance: 0.75,
      delayMs: { min: 360_000, max: 720_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.bio.hold.lift", polarity: "TEMPLATE", strengthScale: 0.7 },
        { probability: 0.5, templateId: "seq.bio.hold.drop", polarity: "TEMPLATE", strengthScale: 0.7 },
      ],
    },
    slots: {
      product: { kind: "pick", vocab: "product" },
      country: { kind: "pick", vocab: "country" },
    },
  },
  {
    id: "co.bio.approval",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.55, max: 0.82 },
    headlines: ["{name} {product}, {country} 품목허가 획득… 연내 출시"],
    sectors: ["BIO"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      country: { kind: "pick", vocab: "country" },
    },
  },

  // ── 엔터 ───────────────────────────────────────────────────
  {
    id: "co.ent.comeback",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name} 소속 아티스트 신보, 초동 {count} 돌파… 자체 최고"],
    sectors: ["ENTERTAINMENT"],
    slots: { count: { kind: "count", range: { min: 800_000, max: 3_000_000 }, unit: "장" } },
  },
  {
    id: "co.ent.tour",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name}, {country} 포함 {count} 월드투어 전석 매진"],
    sectors: ["ENTERTAINMENT"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      count: { kind: "count", range: { min: 20, max: 60 }, unit: "회" },
    },
  },
  {
    id: "co.ent.contract.dispute",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.5, max: 0.78 },
    headlines: ["{name} 핵심 아티스트, 전속계약 해지 소송 제기"],
    sectors: ["ENTERTAINMENT"],
    followUp: {
      chance: 0.75,
      delayMs: { min: 360_000, max: 720_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.ent.resign", polarity: "TEMPLATE", strengthScale: 0.7 },
        { probability: 0.5, templateId: "seq.ent.leave", polarity: "TEMPLATE", strengthScale: 0.7 },
      ],
    },
  },
  {
    id: "co.ent.enlist",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name} 주력 그룹 멤버 {count} 동시 입대… 활동 공백 우려"],
    sectors: ["ENTERTAINMENT"],
    slots: { count: { kind: "count", range: { min: 2, max: 4 }, unit: "명" } },
  },

  // ── 게임 ───────────────────────────────────────────────────
  {
    id: "co.game.launch.hit",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.5, max: 0.78 },
    headlines: ["{name} {product}, 출시 {duration} 만에 매출 순위 1위"],
    sectors: ["GAME"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      duration: { kind: "duration", range: { min: 2, max: 10 }, unit: "일" },
    },
  },
  {
    id: "co.game.launch.flop",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.5, max: 0.78 },
    headlines: ["{name} 기대작 {product}, 초기 성과 부진… 이용자 {pct} 이탈"],
    sectors: ["GAME"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      pct: { kind: "percent", range: { min: 30, max: 60 } },
    },
  },

  // ── 항공 ───────────────────────────────────────────────────
  {
    id: "co.airline.pax.record",
    category: "EARNINGS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name}, {quarter} 국제선 여객 {count} 수송… 역대 최대"],
    sectors: ["AIRLINE"],
    slots: {
      quarter: { kind: "quarter" },
      count: { kind: "count", range: { min: 3_000_000, max: 6_000_000 }, unit: "명" },
    },
  },
  {
    id: "co.airline.incident",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name} 여객기 긴급 회항… 당국 특별 안전점검 착수"],
    sectors: ["AIRLINE"],
  },

  // ── 건설 ───────────────────────────────────────────────────
  {
    id: "co.construction.redevelop",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name}, {money} 규모 재건축 시공권 확보"],
    sectors: ["CONSTRUCTION"],
    slots: { money: { kind: "money", capFraction: { min: 0.08, max: 0.3 } } },
  },
  {
    id: "co.construction.unsold",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name} 분양 단지 청약 미달… 미분양 {count} 발생"],
    sectors: ["CONSTRUCTION"],
    slots: { count: { kind: "count", range: { min: 300, max: 1_500 }, unit: "가구" } },
  },

  // ── 통신 ───────────────────────────────────────────────────
  {
    id: "co.telecom.subscribers",
    category: "EARNINGS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{name}, 5G 가입자 {count} 돌파… 가입자당 매출 개선"],
    sectors: ["TELECOM"],
    slots: { count: { kind: "count", range: { min: 10_000_000, max: 18_000_000 }, unit: "명" } },
  },
  {
    id: "co.telecom.outage",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.38, max: 0.6 },
    headlines: ["{name} 전국 통신 장애 발생… 이용자 보상안 검토"],
    sectors: ["TELECOM"],
  },

  // ── 식품 ───────────────────────────────────────────────────
  {
    id: "co.food.price.hike",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{name}, 주요 제품 가격 {pct} 인상… 수익성 개선 기대"],
    sectors: ["FOOD"],
    slots: { pct: { kind: "percent", range: { min: 5, max: 12 } } },
  },
  {
    id: "co.food.hit",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{name} {product}, 출시 {duration} 만에 판매 {count} 돌파"],
    sectors: ["FOOD"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      duration: { kind: "duration", range: { min: 2, max: 8 }, unit: "개월" },
      count: { kind: "count", range: { min: 10_000_000, max: 50_000_000 }, unit: "개" },
    },
  },
  {
    id: "co.food.contamination",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name} 일부 제품서 이물질 검출… 자발적 회수 결정"],
    sectors: ["FOOD"],
    followUp: {
      chance: 0.7,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.45, templateId: "seq.recall.expand", polarity: "SAME", strengthScale: 0.8 },
        { probability: 0.55, templateId: "seq.recall.close", polarity: "REVERSE", strengthScale: 0.6 },
      ],
    },
  },

  // ── 반도체·전자 ────────────────────────────────────────────
  {
    id: "co.semi.supply.deal",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.55, max: 0.82 },
    headlines: ["{name}, 글로벌 빅테크에 {product} 공급 확정… {money} 규모"],
    sectors: ["SEMICONDUCTOR", "ELECTRONICS"],
    volumeMultiplier: { min: 1.4, max: 1.8 },
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.1, max: 0.35 } },
    },
  },
  {
    id: "co.semi.yield",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.45, max: 0.7 },
    headlines: ["{name} {product} 수율 난항… 양산 일정 {duration} 지연"],
    sectors: ["SEMICONDUCTOR", "ELECTRONICS"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      duration: { kind: "duration", range: { min: 2, max: 6 }, unit: "개월" },
    },
  },

  // ── 2차전지 ────────────────────────────────────────────────
  {
    id: "co.battery.fire",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.5, max: 0.78 },
    headlines: ["{name} 배터리 탑재 차량 화재 잇따라… 원인 조사 착수"],
    sectors: ["BATTERY"],
    followUp: {
      chance: 0.75,
      delayMs: { min: 360_000, max: 720_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.battery.fire.clear", polarity: "TEMPLATE", strengthScale: 0.7 },
        { probability: 0.5, templateId: "seq.battery.fire.cause", polarity: "TEMPLATE", strengthScale: 0.7 },
      ],
    },
  },
  {
    id: "co.battery.supply",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.55, max: 0.82 },
    headlines: ["{name}, {country} 완성차와 {money} 규모 {product} 장기 공급계약"],
    sectors: ["BATTERY"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      money: { kind: "money", capFraction: { min: 0.3, max: 1 } },
      product: { kind: "pick", vocab: "product" },
    },
  },

  // ── 중공업·상사·증권 ────────────────────────────────────────
  {
    id: "co.heavy.lng.order",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.5, max: 0.78 },
    headlines: ["{name}, LNG 운반선 {count} 수주… 총 {money}"],
    sectors: ["HEAVY"],
    slots: {
      count: { kind: "count", range: { min: 2, max: 10 }, unit: "척" },
      money: { kind: "money", capFraction: { min: 0.05, max: 0.25 } },
    },
  },
  {
    id: "co.trading.mine",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name}, {country} 광산 지분 인수로 {commodity} 장기 물량 확보"],
    sectors: ["TRADING"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      commodity: { kind: "pick", vocab: "commodity" },
    },
  },
  {
    id: "co.broker.ipo.lead",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{name}, 대형 IPO 대표주관 수임… 수수료 {money} 기대"],
    sectors: ["BROKER"],
    slots: { money: { kind: "money", capFraction: { min: 0.003, max: 0.01 }, minEok: 50 } },
  },
  {
    id: "co.broker.loss",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name}, 해외 부동산 투자 손실 {money} 반영"],
    sectors: ["BROKER"],
    slots: { money: { kind: "money", capFraction: { min: 0.02, max: 0.08 } } },
  },

  // ── 업종 무관: 지배구조·수급 ────────────────────────────────
  {
    id: "co.activist",
    category: "FLOW",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["행동주의 펀드, {name} 지분 {pct} 확보… 주주환원 확대 요구"],
    slots: { pct: { kind: "percent", range: { min: 3, max: 7 } } },
  },
  {
    id: "co.short.report",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.5, max: 0.78 },
    headlines: ["해외 공매도 리서치, {name} 회계 처리 의혹 제기… 회사 측 '사실무근'"],
    followUp: {
      chance: 0.75,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.short.rebut", polarity: "TEMPLATE", strengthScale: 0.7 },
        { probability: 0.5, templateId: "seq.short.probe", polarity: "TEMPLATE", strengthScale: 0.7 },
      ],
    },
  },
  {
    id: "co.governance.dispute",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name}, 경영권 분쟁 격화… 임시 주주총회 소집 청구"],
    followUp: {
      chance: 0.75,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.gov.settle", polarity: "TEMPLATE", strengthScale: 0.7 },
        { probability: 0.5, templateId: "seq.gov.proxy", polarity: "TEMPLATE", strengthScale: 0.7 },
      ],
    },
  },
  {
    id: "co.takeover.rumor",
    category: "CAPITAL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.45, max: 0.72 },
    headlines: ["{name}, 글로벌 사모펀드 인수설… 회사 측 '다양한 방안 검토 중'"],
    volumeMultiplier: { min: 1.4, max: 1.9 },
    followUp: {
      chance: 0.9,
      delayMs: { min: 120_000, max: 420_000 },
      outcomes: [
        { probability: 0.45, templateId: "seq.ma.confirm", polarity: "SAME", strengthScale: 0.6 },
        { probability: 0.55, templateId: "seq.ma.deny", polarity: "REVERSE", strengthScale: 0.85 },
      ],
    },
  },
  {
    id: "co.ai.cost.cut",
    category: "BUSINESS",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{name}, 전사 AI 도입으로 연간 비용 {money} 절감 전망"],
    slots: { money: { kind: "money", capFraction: { min: 0.005, max: 0.02 }, minEok: 30 } },
  },
  {
    id: "co.overhang",
    category: "FLOW",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name} 2대주주, 보유 지분 {pct} 매각 추진… 오버행 우려"],
    slots: { pct: { kind: "percent", range: { min: 4, max: 12 } } },
    followUp: {
      chance: 0.75,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.5, templateId: "seq.overhang.withdraw", polarity: "TEMPLATE", strengthScale: 0.7 },
        { probability: 0.5, templateId: "seq.overhang.discount", polarity: "TEMPLATE", strengthScale: 0.7 },
      ],
    },
  },

  // ── 위 기사들의 후속 보도 ───────────────────────────────────
  {
    id: "seq.short.rebut",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name}, 공매도 리포트 반박 자료 공개… 외부 감사인 '문제없음'"],
  },
  {
    id: "seq.short.probe",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["금융당국, {name} 회계 처리 조사 착수… 의혹 확산"],
  },
  {
    id: "seq.ent.resign",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name}, 핵심 아티스트와 분쟁 합의… 재계약 체결"],
  },
  {
    id: "seq.ent.leave",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 핵심 아티스트 결별 확정… 매출 공백 불가피"],
  },
  {
    id: "seq.bio.hold.lift",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 임상 중단 조치 해제… 개발 일정 정상화"],
  },
  {
    id: "seq.bio.hold.drop",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name}, 해당 파이프라인 개발 포기 결정… 손상차손 반영"],
  },
  {
    id: "seq.battery.fire.clear",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 배터리, 차량 화재와 무관 결론… 불확실성 해소"],
  },
  {
    id: "seq.battery.fire.cause",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 셀 결함이 화재 원인 결론… 대규모 리콜 불가피"],
  },
  {
    id: "seq.gov.settle",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 경영권 분쟁 합의… 공동 경영 체제로 전환"],
  },
  {
    id: "seq.gov.proxy",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 표 대결 장기화… 경영 공백 우려"],
  },
  {
    id: "seq.overhang.withdraw",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 2대주주, 지분 매각 계획 철회… 오버행 해소"],
  },
  {
    id: "seq.overhang.discount",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.7 },
    headlines: ["{name} 2대주주 지분 블록딜 완료… 할인율 커 주가 부담"],
  },
];
