import type { NewsTemplate } from "../types";

/**
 * 시장 전체 추가분 — 해외 지표·원자재·위험선호. macro.ts와 같은 규칙: 회사 이름 없음,
 * 채널과 방향 필수, 오르는 쪽/내리는 쪽 개수를 맞춰 시장에 한쪽 쏠림이 생기지 않게 한다.
 */
export const MACRO_EXTRA_TEMPLATES: readonly NewsTemplate[] = [
  {
    id: "macro.ppi.cool",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["생산자물가 {pct} 하락… 기업 원가 부담 완화 기대"],
    slots: { pct: { kind: "percent", range: { min: 0.3, max: 1.5 } } },
  },
  {
    id: "macro.ppi.hot",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["생산자물가 {pct} 상승… 인플레이션 압력 확대"],
    slots: { pct: { kind: "percent", range: { min: 0.5, max: 2 } } },
  },
  {
    id: "macro.us.cpi.cool",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["미국 소비자물가 {pct}로 둔화… 연준 조기 인하 기대 확산"],
    slots: { pct: { kind: "percent", range: { min: 2, max: 2.8 } } },
  },
  {
    id: "macro.us.cpi.hot",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["미국 소비자물가 {pct} 상승… 긴축 장기화 우려에 채권금리 급등"],
    slots: { pct: { kind: "percent", range: { min: 3.4, max: 4.5 } } },
  },
  {
    id: "macro.gas.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "OIL",
    macroDirection: 1,
    referenceMoves: { GAS: 1, OIL: 0.2 },
    strength: { min: 0.28, max: 0.48 },
    headlines: ["유럽 천연가스 가격 {pct} 급등… 에너지 위기 재점화"],
    slots: { pct: { kind: "percent", range: { min: 12, max: 35 }, reference: true } },
  },
  {
    id: "macro.gas.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "OIL",
    macroDirection: -1,
    referenceMoves: { GAS: 1, OIL: 0.2 },
    strength: { min: 0.28, max: 0.48 },
    headlines: ["천연가스 가격 {pct} 급락… 에너지 비용 하락 기대"],
    slots: { pct: { kind: "percent", range: { min: 10, max: 30 }, reference: true } },
  },
  {
    id: "macro.pmi.up",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["글로벌 제조업 PMI {level} 기록… 경기 확장 국면 진입"],
    slots: { level: { kind: "level", range: { min: 51.5, max: 54.5 }, unit: "", decimals: 1 } },
  },
  {
    id: "macro.pmi.down",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["글로벌 제조업 PMI {level}{로} 위축… 경기 둔화 신호"],
    slots: { level: { kind: "level", range: { min: 45.5, max: 48.8 }, unit: "", decimals: 1 } },
  },
  {
    id: "macro.infra.metals",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "COMMODITY",
    macroDirection: 1,
    referenceMoves: { COPPER: 1 },
    strength: { min: 0.25, max: 0.45 },
    headlines: ["{region} 인프라 투자 확대… 구리·철광석 가격 강세"],
    slots: { region: { kind: "pick", vocab: "region" } },
  },
  {
    id: "macro.metal.inventory",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "COMMODITY",
    macroDirection: -1,
    referenceMoves: "commodity",
    strength: { min: 0.25, max: 0.45 },
    headlines: ["{region} 산업금속 재고 급증… {commodity} 가격 {pct} 하락"],
    slots: {
      region: { kind: "pick", vocab: "region" },
      commodity: { kind: "pick", vocab: "commodity" },
      pct: { kind: "percent", range: { min: 5, max: 15 }, reference: true },
    },
  },
  {
    id: "macro.nasdaq.rally",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    // 안전자산: 위험 회피면 금이 오르고, 위험 선호면 내린다
    referenceMoves: { GOLD: -0.4 },
    strength: { min: 0.3, max: 0.5 },
    headlines: ["나스닥 {pct} 급등… 기술주 랠리에 위험선호 회복"],
    slots: { pct: { kind: "percent", range: { min: 2, max: 4.5 } } },
  },
  {
    id: "macro.nasdaq.crash",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    // 안전자산: 위험 회피면 금이 오르고, 위험 선호면 내린다
    referenceMoves: { GOLD: -0.4 },
    strength: { min: 0.35, max: 0.55 },
    headlines: ["뉴욕증시 급락… 나스닥 {pct} 하락 마감"],
    slots: { pct: { kind: "percent", range: { min: 2.5, max: 5 } } },
  },
  {
    id: "macro.bank.stress",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    // 안전자산: 위험 회피면 금이 오르고, 위험 선호면 내린다
    referenceMoves: { GOLD: -0.4 },
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{region} 중소형 은행 부실 우려 확산… 금융시장 불안"],
    slots: { region: { kind: "pick", vocab: "region" } },
  },
  {
    id: "macro.qt.slowdown",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["연준, 양적긴축 속도 조절 발표… 유동성 우려 완화"],
  },
  {
    id: "macro.won.weak",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "FX",
    macroDirection: 1,
    referenceMoves: { USDKRW: 1 },
    strength: { min: 0.28, max: 0.48 },
    headlines: ["원·달러 환율 {level} 돌파… 수입물가 상승 우려"],
    slots: { level: { kind: "level", range: { min: 1_420, max: 1_490 }, unit: "원", reference: true } },
  },
  {
    id: "macro.ceasefire",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    // 안전자산: 위험 회피면 금이 오르고, 위험 선호면 내린다
    referenceMoves: { GOLD: -0.4 },
    strength: { min: 0.3, max: 0.52 },
    headlines: [
      "중동 분쟁 휴전 합의… 지정학 리스크 완화에 위험자산 강세",
      "동유럽 전쟁 휴전 협상 타결… 위험자산 선호 회복",
    ],
  },
  // ── 금·옥수수 (2026-09-26 선물 상장) ──
  {
    id: "macro.gold.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    // 위험 회피(−1) × 가중치 −1 → 금 상승
    referenceMoves: { GOLD: -1 },
    strength: { min: 0.3, max: 0.55 },
    headlines: [
      "안전자산 쏠림에 금값 {pct} 급등… {duration} 만의 최고",
      "{region} 불안에 금 매수세 몰려… 국제 금 시세 {pct} 상승",
    ],
    slots: {
      pct: { kind: "percent", range: { min: 1, max: 3 }, reference: true },
      duration: { kind: "duration", range: { min: 2, max: 18 }, unit: "개월" },
      region: { kind: "pick", vocab: "region" },
    },
  },
  {
    id: "macro.gold.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    // 위험 선호(+1) × 가중치 −1 → 금 하락
    referenceMoves: { GOLD: -1 },
    strength: { min: 0.25, max: 0.5 },
    headlines: [
      "위험자산 선호 회복에 금값 {pct} 하락",
      "안전자산 수요 둔화… 국제 금 시세 {duration} 만의 최저",
    ],
    slots: {
      pct: { kind: "percent", range: { min: 1, max: 3 }, reference: true },
      duration: { kind: "duration", range: { min: 2, max: 12 }, unit: "개월" },
    },
  },
  {
    id: "macro.corn.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "COMMODITY",
    macroDirection: 1,
    referenceMoves: { CORN: 1 },
    strength: { min: 0.22, max: 0.45 },
    headlines: [
      "미 중서부 가뭄에 옥수수 가격 {pct} 급등… 곡물가 비상",
      "옥수수 작황 부진 전망… 국제 곡물가 {duration} 만의 최고",
    ],
    slots: {
      pct: { kind: "percent", range: { min: 2, max: 5 }, reference: true },
      duration: { kind: "duration", range: { min: 3, max: 24 }, unit: "개월" },
    },
  },
  {
    id: "macro.corn.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "COMMODITY",
    macroDirection: -1,
    referenceMoves: { CORN: 1 },
    strength: { min: 0.2, max: 0.42 },
    headlines: [
      "남미 수확 호조에 옥수수 가격 {pct} 급락",
      "옥수수 풍작 전망… 국제 곡물가 {duration} 만의 최저",
    ],
    slots: {
      pct: { kind: "percent", range: { min: 2, max: 5 }, reference: true },
      duration: { kind: "duration", range: { min: 3, max: 18 }, unit: "개월" },
    },
  },
];
