import type { NewsTemplate } from "../types";

/**
 * 시장 전체 — no company is named. The sentiment recorded here is the market's
 * baseline reading; each symbol's signed macroBeta decides whether the story
 * lands as good or bad news for that particular listing.
 */
export const MACRO_TEMPLATES: readonly NewsTemplate[] = [
  {
    id: "macro.rate.cut",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.5 },
    headlines: [
      "한국은행, 기준금리 {pct}p 인하… 시장 예상보다 빠른 완화",
      "한은 금통위, 기준금리 {pct}p 전격 인하… 경기 방어 우선",
    ],
    slots: { pct: { kind: "percent", range: { min: 0.25, max: 0.5 }, decimals: 1 } },
  },
  {
    id: "macro.rate.hike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.32, max: 0.52 },
    headlines: [
      "한국은행, 기준금리 {pct}p 인상… 긴축 기조 재확인",
      "한은, 기준금리 {pct}p 올려… 물가 안정 '최우선'",
    ],
    slots: { pct: { kind: "percent", range: { min: 0.25, max: 0.5 }, decimals: 1 } },
  },
  {
    id: "macro.cpi.cool",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["소비자물가 상승률 {pct}로 둔화… 금리 인하 기대 확산"],
    slots: { pct: { kind: "percent", range: { min: 1.2, max: 2.6 } } },
  },
  {
    id: "macro.cpi.hot",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["소비자물가 {pct} 상승… 인플레 재점화 우려"],
    slots: { pct: { kind: "percent", range: { min: 3.2, max: 5.5 } } },
  },
  {
    id: "macro.stimulus",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.48 },
    headlines: ["정부, {money} 규모 경기부양 패키지 발표"],
    slots: { money: { kind: "macroMoney", eok: { min: 80_000, max: 350_000 } } },
  },
  {
    id: "macro.creditcrunch",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.4, max: 0.58 },
    headlines: ["회사채 시장 경색… 단기자금 조달금리 {pct}p 급등"],
    slots: { pct: { kind: "percent", range: { min: 0.3, max: 1.2 } } },
  },
  {
    id: "macro.fx.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "FX",
    macroDirection: 1,
    strength: { min: 0.3, max: 0.5 },
    headlines: [
      "원/달러 환율 {level} 돌파… {duration} 만의 최고",
      "달러 강세에 원화 급락… 환율 {level} 위협",
    ],
    slots: {
      level: { kind: "level", range: { min: 1_380, max: 1_480 }, unit: "원" },
      duration: { kind: "duration", range: { min: 6, max: 24 }, unit: "개월" },
    },
  },
  {
    id: "macro.fx.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "FX",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["원/달러 환율 {level}로 하락… {duration} 만의 최저"],
    slots: {
      level: { kind: "level", range: { min: 1_280, max: 1_340 }, unit: "원" },
      duration: { kind: "duration", range: { min: 6, max: 24 }, unit: "개월" },
    },
  },
  {
    id: "macro.oil.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "OIL",
    macroDirection: 1,
    strength: { min: 0.3, max: 0.5 },
    headlines: [
      "국제유가 배럴당 {level} 돌파… 원가 부담 확대",
      "WTI {level}까지 급등… 공급 차질 우려에 유가 들썩",
    ],
    slots: { level: { kind: "level", range: { min: 88, max: 105 }, unit: "달러" } },
  },
  {
    id: "macro.oil.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "OIL",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["국제유가 배럴당 {level}로 하락… 원가 부담 완화"],
    slots: { level: { kind: "level", range: { min: 62, max: 74 }, unit: "달러" } },
  },
  {
    id: "macro.global.rally",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.45 },
    headlines: [
      "뉴욕증시 기술주 급등 마감… 위험자산 선호 회복",
      "나스닥 사상 최고치 경신… 아시아 증시 동반 강세 출발",
    ],
  },
  {
    id: "macro.global.selloff",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.32, max: 0.52 },
    headlines: [
      "간밤 뉴욕증시 급락… 글로벌 위험회피 확산",
      "미 증시 {pct} 급락 마감… 변동성지수 급등",
    ],
    slots: { pct: { kind: "percent", range: { min: 1.5, max: 3.8 } } },
  },
  {
    id: "macro.foreign.inflow",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["외국인, 국내 증시서 {money} 순매수… {duration} 연속 '사자'"],
    slots: {
      money: { kind: "macroMoney", eok: { min: 8_000, max: 45_000 } },
      duration: { kind: "duration", range: { min: 3, max: 12 }, unit: "거래일" },
    },
  },
  {
    id: "macro.geopolitics",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.35, max: 0.55 },
    headlines: ["{country} 지정학 리스크 고조… 아시아 증시 일제히 약세"],
    slots: { country: { kind: "pick", vocab: "country" } },
  },
  {
    id: "macro.valueup",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.45 },
    headlines: ["정부, 배당소득 분리과세 등 밸류업 세제 확정"],
  },

  // ── 금리·통화정책 ──
  {
    id: "macro.fed.cut",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{centralBank}, 기준금리 {pct}p 인하… 글로벌 완화 사이클 진입", "{centralBank} 금리 인하에 신흥국 자금 유입 기대"],
    slots: { centralBank: { kind: "pick", vocab: "centralBank" }, pct: { kind: "percent", range: { min: 0.25, max: 0.5 }, decimals: 1 } },
  },
  {
    id: "macro.fed.hawkish",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{centralBank} '금리 더 오래 높게'… 조기 인하 기대 후퇴", "{centralBank} 의사록 매파적… 국채금리 급등"],
    slots: { centralBank: { kind: "pick", vocab: "centralBank" } },
  },
  {
    id: "macro.bond.yield.up",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.45 },
    headlines: ["미 10년물 국채금리 {pct} 돌파… 성장주 밸류에이션 부담", "국고채 3년물 금리 {pct}… {duration} 만의 최고"],
    slots: { pct: { kind: "percent", range: { min: 3.6, max: 5.2 } }, duration: { kind: "duration", range: { min: 3, max: 18 }, unit: "개월" } },
  },
  {
    id: "macro.bond.yield.down",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["국채금리 급락… 시장, 연내 {count} 인하 반영", "미 국채금리 {pct}로 하락… 위험자산에 온기"],
    slots: { count: { kind: "count", range: { min: 2, max: 4 }, unit: "차례" }, pct: { kind: "percent", range: { min: 3.2, max: 4.1 } } },
  },
  {
    id: "macro.jobs.hot",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.22, max: 0.4 },
    headlines: ["미 고용 {count} 증가 '깜짝'… 금리 인하 시점 늦춰지나"],
    slots: { count: { kind: "count", range: { min: 25, max: 38 }, unit: "만 명" } },
  },
  {
    id: "macro.household.debt",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["가계대출 {money} 급증… 금융당국, 대출 규제 강화 예고"],
    slots: { money: { kind: "macroMoney", eok: { min: 40_000, max: 120_000 } } },
  },
  // ── 환율 ──
  {
    id: "macro.fx.intervene",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "FX",
    macroDirection: -1,
    strength: { min: 0.22, max: 0.4 },
    headlines: ["외환당국 구두개입에 환율 {level}로 급락", "당국 '환율 쏠림 예의주시'… 원화 강세 전환"],
    slots: { level: { kind: "level", range: { min: 1_300, max: 1_360 }, unit: "원" } },
  },
  {
    id: "macro.fx.yen",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "FX",
    macroDirection: 1,
    strength: { min: 0.22, max: 0.4 },
    headlines: ["엔화 {duration} 만의 최저… 원화도 동반 약세", "달러인덱스 {level} 돌파… 아시아 통화 일제히 약세"],
    slots: { duration: { kind: "duration", range: { min: 12, max: 34 }, unit: "년" }, level: { kind: "level", range: { min: 104, max: 110 }, unit: "" } },
  },
  {
    id: "macro.fx.reserve",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "FX",
    macroDirection: -1,
    strength: { min: 0.2, max: 0.36 },
    headlines: ["외환보유액 {money} 증가… 원화 안정세, 환율 {level}대로"],
    slots: { money: { kind: "macroMoney", eok: { min: 20_000, max: 90_000 } }, level: { kind: "level", range: { min: 1_290, max: 1_340 }, unit: "원" } },
  },
  {
    id: "macro.fx.dollar.rally",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "FX",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.45 },
    headlines: ["안전자산 선호에 '킹달러'… 환율 {level} 재돌파", "{region} 위기설에 달러 급등… 환율 {level}"],
    slots: { level: { kind: "level", range: { min: 1_390, max: 1_470 }, unit: "원" }, region: { kind: "pick", vocab: "region" } },
  },
  // ── 유가 ──
  {
    id: "macro.opec.cut",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "OIL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["OPEC+, 하루 {count} 추가 감산 합의… 유가 급등", "산유국 감산 연장에 브렌트유 {level} 돌파"],
    slots: { count: { kind: "count", range: { min: 50, max: 200 }, unit: "만 배럴" }, level: { kind: "level", range: { min: 90, max: 108 }, unit: "달러" } },
  },
  {
    id: "macro.opec.raise",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "OIL",
    macroDirection: -1,
    strength: { min: 0.25, max: 0.45 },
    headlines: ["OPEC+ 증산 결정… 유가 {pct} 급락", "미 원유 재고 {count} 급증… 유가 {level}로 하락"],
    slots: {
      pct: { kind: "percent", range: { min: 3, max: 7 } },
      count: { kind: "count", range: { min: 400, max: 1_200 }, unit: "만 배럴" },
      level: { kind: "level", range: { min: 64, max: 76 }, unit: "달러" },
    },
  },
  {
    id: "macro.oil.mideast",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "OIL",
    macroDirection: 1,
    strength: { min: 0.32, max: 0.52 },
    headlines: ["중동 긴장 고조에 유가 {pct} 급등… 공급 차질 우려", "호르무즈 해협 긴장… 국제유가 {level} 근접"],
    slots: { pct: { kind: "percent", range: { min: 3, max: 8 } }, level: { kind: "level", range: { min: 92, max: 110 }, unit: "달러" } },
  },
  {
    id: "macro.oil.demand.weak",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "OIL",
    macroDirection: -1,
    strength: { min: 0.22, max: 0.4 },
    headlines: ["{region} 수요 둔화 우려에 유가 {duration} 만의 최저"],
    slots: { region: { kind: "pick", vocab: "region" }, duration: { kind: "duration", range: { min: 3, max: 14 }, unit: "개월" } },
  },
  // ── 원자재·운임 ──
  {
    id: "macro.metal.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "COMMODITY",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["{commodity} 가격 {pct} 급등… {duration} 만의 최고", "{region} 인프라 투자 기대에 {commodity} 랠리"],
    slots: {
      commodity: { kind: "pick", vocab: "commodity" },
      pct: { kind: "percent", range: { min: 4, max: 12 } },
      duration: { kind: "duration", range: { min: 6, max: 30 }, unit: "개월" },
      region: { kind: "pick", vocab: "region" },
    },
  },
  {
    id: "macro.metal.slump",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "COMMODITY",
    macroDirection: -1,
    strength: { min: 0.26, max: 0.46 },
    headlines: ["{commodity} 가격 {pct} 급락… 재고 급증에 수요 둔화 우려", "{region} 경기 부진에 {commodity} 시세 {duration} 만의 최저"],
    slots: {
      commodity: { kind: "pick", vocab: "commodity" },
      pct: { kind: "percent", range: { min: 4, max: 11 } },
      region: { kind: "pick", vocab: "region" },
      duration: { kind: "duration", range: { min: 6, max: 30 }, unit: "개월" },
    },
  },
  {
    id: "macro.metal.supply",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "COMMODITY",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["{country} 대형 {commodity} 광산 가동 중단… 공급 차질 우려", "{country}, {commodity} 수출 통제 검토… 원자재 가격 들썩"],
    slots: { country: { kind: "pick", vocab: "country" }, commodity: { kind: "pick", vocab: "commodity" } },
  },
  {
    id: "macro.freight.up",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "COMMODITY",
    macroDirection: 1,
    strength: { min: 0.22, max: 0.4 },
    headlines: ["해상운임지수 {pct} 급등… {duration} 연속 상승", "컨테이너 운임 {level} 돌파… 물류비 부담 커진다"],
    slots: {
      pct: { kind: "percent", range: { min: 5, max: 15 } },
      duration: { kind: "duration", range: { min: 3, max: 9 }, unit: "일" },
      level: { kind: "level", range: { min: 2_400, max: 4_200 }, unit: "" },
    },
  },
  {
    id: "macro.freight.down",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "COMMODITY",
    macroDirection: -1,
    strength: { min: 0.2, max: 0.38 },
    headlines: ["해상운임 {pct} 급락… 물동량 둔화 신호", "벌크선 운임지수 {duration} 만의 최저"],
    slots: { pct: { kind: "percent", range: { min: 5, max: 14 } }, duration: { kind: "duration", range: { min: 4, max: 20 }, unit: "개월" } },
  },
  // ── 글로벌·거시 ──
  {
    id: "macro.china.stimulus",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["중국, {money} 규모 대규모 부양책… 아시아 증시 환호", "중국 지급준비율 {pct}p 인하… 경기 부양 본격화"],
    slots: { money: { kind: "macroMoney", eok: { min: 1_500_000, max: 6_000_000 } }, pct: { kind: "percent", range: { min: 0.25, max: 0.5 }, decimals: 1 } },
  },
  {
    id: "macro.china.slump",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["중국 제조업 PMI {level}… {duration} 연속 위축", "중국 부동산 위기 재부각… 아시아 증시 약세"],
    slots: { level: { kind: "level", range: { min: 47, max: 49.8 }, unit: "", decimals: 1 }, duration: { kind: "duration", range: { min: 3, max: 8 }, unit: "개월" } },
  },
  {
    id: "macro.tariff",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.32, max: 0.52 },
    headlines: ["{country}, 수입품에 {pct} 관세 부과 발표… 무역전쟁 우려", "{country} 관세 폭탄에 수출주 급락"],
    slots: { country: { kind: "pick", vocab: "country" }, pct: { kind: "percent", range: { min: 10, max: 30 }, decimals: 0 } },
  },
  {
    id: "macro.trade.deal",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["{country}{과} 관세 협상 타결… 불확실성 해소", "{country} 무역 합의 임박 보도에 위험선호 회복"],
    slots: { country: { kind: "pick", vocab: "country" } },
  },
  {
    id: "macro.export.record",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.24, max: 0.42 },
    headlines: ["월간 수출 {pct} 증가… {duration} 연속 플러스", "반도체 수출 호조에 무역수지 {money} 흑자"],
    slots: {
      pct: { kind: "percent", range: { min: 5, max: 18 }, decimals: 1 },
      duration: { kind: "duration", range: { min: 4, max: 14 }, unit: "개월" },
      money: { kind: "macroMoney", eok: { min: 30_000, max: 90_000 } },
    },
  },
  {
    id: "macro.gdp.miss",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.26, max: 0.44 },
    headlines: ["{quarter} GDP 성장률 {pct}… 시장 예상 하회", "경기선행지수 {duration} 연속 하락… 경기 둔화 경고음"],
    slots: {
      quarter: { kind: "quarter", offsetQuarters: -1 },
      pct: { kind: "percent", range: { min: -0.4, max: 0.5 }, decimals: 1 },
      duration: { kind: "duration", range: { min: 3, max: 7 }, unit: "개월" },
    },
  },
  {
    id: "macro.vix.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["공포지수 {level} 급등… 글로벌 증시 투매", "{region} 은행 위기설에 안전자산 쏠림"],
    slots: { level: { kind: "level", range: { min: 24, max: 38 }, unit: "" }, region: { kind: "pick", vocab: "region" } },
  },
  {
    id: "macro.recession.fear",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["{region} 경기침체 공포 확산… 제조업 지표 {duration} 연속 부진", "장단기 금리 역전 심화… 'R의 공포' 재점화"],
    slots: { region: { kind: "pick", vocab: "region" }, duration: { kind: "duration", range: { min: 3, max: 9 }, unit: "개월" } },
  },
  {
    id: "macro.short.resume",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.22, max: 0.4 },
    headlines: ["공매도 전면 재개 첫날… 대형주 변동성 확대"],
  },
  {
    id: "macro.msci",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["MSCI 선진국지수 편입 관찰대상국 지정… 외국인 자금 유입 기대", "정부, 외환시장 24시간 개방 확정… 선진지수 편입 기대 확산"],
  },
];
