import type { NewsTemplate } from "../types";

/**
 * 시장 전체 — no company is named. The sentiment recorded here is the market's
 * baseline reading; each symbol's signed macroBeta decides whether the story
 * lands as good or bad news for that particular listing.
 */
export const MACRO_TEMPLATES: readonly NewsTemplate[] = [
  {
    id: "macro.rate.cut",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["한국은행, 기준금리 {pct}p 인하… 시장 예상보다 빠른 완화"],
    slots: { pct: { kind: "percent", range: { min: 0.25, max: 0.5 }, decimals: 1 } },
  },
  {
    id: "macro.rate.hike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.32, max: 0.52 },
    headlines: ["한국은행, 기준금리 {pct}p 인상… 긴축 기조 재확인"],
    slots: { pct: { kind: "percent", range: { min: 0.25, max: 0.5 }, decimals: 1 } },
  },
  {
    id: "macro.cpi.cool",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["소비자물가 상승률 {pct}로 둔화… 금리 인하 기대 확산"],
    slots: { pct: { kind: "percent", range: { min: 1.2, max: 2.6 } } },
  },
  {
    id: "macro.cpi.hot",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["소비자물가 {pct} 상승… 인플레 재점화 우려"],
    slots: { pct: { kind: "percent", range: { min: 3.2, max: 5.5 } } },
  },
  {
    id: "macro.stimulus",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "RATE",
    macroDirection: -1,
    strength: { min: 0.3, max: 0.48 },
    headlines: ["정부, {money} 규모 경기부양 패키지 발표"],
    slots: { money: { kind: "macroMoney", eok: { min: 80_000, max: 350_000 } } },
  },
  {
    id: "macro.creditcrunch",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "RATE",
    macroDirection: 1,
    strength: { min: 0.4, max: 0.58 },
    headlines: ["회사채 시장 경색… 단기자금 조달금리 {pct}p 급등"],
    slots: { pct: { kind: "percent", range: { min: 0.3, max: 1.2 } } },
  },
  {
    id: "macro.fx.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "FX",
    macroDirection: 1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["원/달러 환율 {level} 돌파… {duration} 만의 최고"],
    slots: {
      level: { kind: "level", range: { min: 1_380, max: 1_480 }, unit: "원" },
      duration: { kind: "duration", range: { min: 6, max: 24 }, unit: "개월" },
    },
  },
  {
    id: "macro.fx.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "FX",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["원/달러 환율 {level}로 하락… {duration} 만의 최저"],
    slots: {
      level: { kind: "level", range: { min: 1_280, max: 1_340 }, unit: "원" },
      duration: { kind: "duration", range: { min: 6, max: 24 }, unit: "개월" },
    },
  },
  {
    id: "macro.oil.spike",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "OIL",
    macroDirection: 1,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["국제유가 배럴당 {level} 돌파… 원가 부담 확대"],
    slots: { level: { kind: "level", range: { min: 88, max: 105 }, unit: "달러" } },
  },
  {
    id: "macro.oil.drop",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "OIL",
    macroDirection: -1,
    strength: { min: 0.28, max: 0.46 },
    headlines: ["국제유가 배럴당 {level}로 하락… 원가 부담 완화"],
    slots: { level: { kind: "level", range: { min: 62, max: 74 }, unit: "달러" } },
  },
  {
    id: "macro.global.rally",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.45 },
    headlines: ["뉴욕증시 기술주 급등 마감… 위험자산 선호 회복"],
  },
  {
    id: "macro.global.selloff",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.32, max: 0.52 },
    headlines: ["간밤 뉴욕증시 급락… 글로벌 위험회피 확산"],
  },
  {
    id: "macro.foreign.inflow",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.25, max: 0.42 },
    headlines: ["외국인, 국내 증시서 {money} 순매수… {duration} 연속 '사자'"],
    slots: {
      money: { kind: "macroMoney", eok: { min: 8_000, max: 45_000 } },
      duration: { kind: "duration", range: { min: 3, max: 12 }, unit: "거래일" },
    },
  },
  {
    id: "macro.geopolitics",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "NEGATIVE",
    macroChannel: "GLOBAL",
    macroDirection: -1,
    strength: { min: 0.35, max: 0.55 },
    headlines: ["{country} 지정학 리스크 고조… 아시아 증시 일제히 약세"],
    slots: { country: { kind: "pick", vocab: "country" } },
  },
  {
    id: "macro.valueup",
    category: "MACRO",
    scope: "MACRO",
    sentiment: "POSITIVE",
    macroChannel: "GLOBAL",
    macroDirection: 1,
    strength: { min: 0.28, max: 0.45 },
    headlines: ["정부, 배당소득 분리과세 등 밸류업 세제 확정"],
  },
];
