import type { NewsTemplate } from "../types";

/** 리스크 — 리콜·소송·제재·사고·지배구조 */
export const RISK_TEMPLATES: readonly NewsTemplate[] = [
  {
    id: "risk.recall",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.5, max: 0.72 },
    headlines: ["{name}, {product} {count} 자발적 리콜… 비용 {money} 추산"],
    // A recall counts units, so it only fits mass-produced goods. Heavy
    // industry gets the defect story below instead.
    sectors: ["ELECTRONICS", "MATERIALS", "BIO", "AUTO", "BATTERY"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      count: { kind: "count", range: { min: 5_000, max: 400_000 }, unit: "개" },
      money: { kind: "money", capFraction: { min: 0.004, max: 0.03 } },
    },
    followUp: {
      chance: 0.5,
      delayMs: { min: 240_000, max: 600_000 },
      outcomes: [
        { probability: 0.45, templateId: "seq.recall.expand", polarity: "SAME", strengthScale: 0.8 },
        { probability: 0.55, templateId: "seq.recall.close", polarity: "REVERSE", strengthScale: 0.6 },
      ],
    },
  },
  {
    // The heavy-industry equivalent of a recall: one delivered unit, reworked.
    id: "risk.defect",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.45, max: 0.68 },
    headlines: ["{name}, 인도한 {product}에서 결함 발견… 보수 비용 {money} 반영"],
    sectors: ["HEAVY", "TRADING"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.004, max: 0.03 } },
    },
  },
  {
    id: "risk.lawsuit",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.42, max: 0.62 },
    headlines: ["{name}, {country} {counterparty}{로}부터 {money} 손해배상 피소"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      counterparty: { kind: "pick", vocab: "counterparty" },
      money: { kind: "money", capFraction: { min: 0.005, max: 0.04 } },
    },
    followUp: {
      chance: 0.5,
      delayMs: { min: 300_000, max: 720_000 },
      outcomes: [
        { probability: 0.55, templateId: "seq.legal.expand", polarity: "SAME", strengthScale: 0.7 },
        { probability: 0.45, templateId: "seq.legal.settle", polarity: "REVERSE", strengthScale: 0.7 },
      ],
    },
  },
  {
    id: "risk.lawsuit.win",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.38, max: 0.58 },
    headlines: ["{name}, {money} 규모 소송 승소… 불확실성 해소"],
    slots: { money: { kind: "money", capFraction: { min: 0.005, max: 0.04 } } },
  },
  {
    id: "risk.lawsuit.lose",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.55, max: 0.78 },
    headlines: ["{name}, 1심서 패소… {money} 배상 판결"],
    slots: { money: { kind: "money", capFraction: { min: 0.005, max: 0.04 } } },
  },
  {
    id: "risk.sanction",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.5, max: 0.72 },
    headlines: [
      "{agency}, {name}에 과징금 {money} 부과",
      "{agency}, {name} 제재 착수… 영업 일부 정지 검토",
    ],
    slots: {
      agency: { kind: "pick", vocab: "agency" },
      money: { kind: "money", capFraction: { min: 0.002, max: 0.02 } },
    },
  },
  {
    id: "risk.tax",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.38, max: 0.58 },
    headlines: [
      "국세청, {name} 특별 세무조사 착수",
      "{name}, 세무조사서 {money} 추징 통보받아",
    ],
    slots: { money: { kind: "money", capFraction: { min: 0.003, max: 0.025 } } },
  },
  {
    id: "risk.accident",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.48, max: 0.7 },
    headlines: ["{name} {plant} 공장 화재… 생산라인 {duration} 가동 중단"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      plant: { kind: "pick", vocab: "plant" },
      duration: { kind: "duration", range: { min: 3, max: 45 }, unit: "일" },
    },
  },
  {
    id: "risk.strike",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.55 },
    headlines: ["{name} 노조, 파업 돌입… 임금협상 결렬"],
    excludeSectors: ["BROKER", "REIT"],
  },
  {
    id: "risk.strike.end",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.25, max: 0.42 },
    headlines: ["{name} 노사, 임단협 타결… {plant} 정상 조업 재개"],
    excludeSectors: ["BROKER", "REIT"],
    slots: { plant: { kind: "pick", vocab: "plant" } },
  },
  {
    id: "risk.embezzle",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.8, max: 1 },
    headlines: [
      "{name} {title}, {money} 횡령·배임 혐의로 고발",
      "검찰, {name} 본사 압수수색… 배임 혐의 수사",
    ],
    persistence: { min: 0.96, max: 0.985 },
    volumeMultiplier: { min: 1.6, max: 2 },
    slots: {
      title: { kind: "pick", vocab: "title" },
      money: { kind: "money", capFraction: { min: 0.003, max: 0.03 } },
    },
    followUp: {
      chance: 0.8,
      delayMs: { min: 240_000, max: 600_000 },
      outcomes: [
        { probability: 0.65, templateId: "seq.embezzle.indict", polarity: "SAME", strengthScale: 0.7 },
        { probability: 0.35, templateId: "seq.embezzle.clear", polarity: "REVERSE", strengthScale: 0.95 },
      ],
    },
  },
  {
    id: "risk.delisting",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.85, max: 1 },
    headlines: ["{name}, 상장폐지 실질심사 대상 여부 검토… 거래 정지 우려"],
    persistence: { min: 0.965, max: 0.988 },
    volumeMultiplier: { min: 1.7, max: 2 },
  },
  {
    id: "risk.audit",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.78, max: 0.95 },
    headlines: ["{name}, 감사의견 '한정'… 관리종목 지정 우려"],
    persistence: { min: 0.96, max: 0.985 },
  },
  {
    id: "risk.ceo.out",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.55 },
    headlines: ["{name} {title} 전격 사임… 후임 미정"],
    slots: { title: { kind: "pick", vocab: "title" } },
  },
  {
    id: "risk.ceo.in",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.25, max: 0.42 },
    headlines: ["{name}, 신임 {title}에 {counterparty} 출신 인사 선임"],
    slots: {
      title: { kind: "pick", vocab: "title" },
      counterparty: { kind: "pick", vocab: "counterparty" },
    },
  },
  {
    id: "risk.disclosure",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.58 },
    headlines: ["{name}, 불성실공시법인 지정… 벌점 {count}"],
    slots: { count: { kind: "count", range: { min: 2, max: 12 }, unit: "점" } },
  },
  {
    id: "risk.pf",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.55, max: 0.78 },
    headlines: ["{name}, 부동산 PF 대손충당금 {money} 추가 적립"],
    sectors: ["BROKER"],
    slots: { money: { kind: "money", capFraction: { min: 0.02, max: 0.09 } } },
  },

  {
    id: "risk.fire",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name} {plant} 공장 화재… 생산라인 일부 가동 중단", "{name} {plant} 사업장 화재로 {duration} 생산 차질 예상"],
    excludeSectors: ["BROKER", "REIT"],
    volumeMultiplier: { min: 1.3, max: 1.7 },
    slots: {
      plant: { kind: "pick", vocab: "plant" },
      duration: { kind: "duration", range: { min: 1, max: 6 }, unit: "개월" },
    },
  },
  {
    id: "risk.data.leak",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{name}, 고객정보 {count} 유출… {agency} 조사 착수", "{name} 해킹 공격에 내부 시스템 일시 마비"],
    slots: {
      count: { kind: "count", range: { min: 20, max: 300 }, unit: "만 건" },
      agency: { kind: "pick", vocab: "agency" },
    },
  },
  {
    id: "risk.insider.sell",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.28, max: 0.45 },
    headlines: ["{name} {title}, 보유주식 {money} 장내 매도", "{name} 임원진 잇단 지분 매도… 고점 신호?"],
    slots: {
      title: { kind: "pick", vocab: "title" },
      money: { kind: "money", capFraction: { min: 0.002, max: 0.01 } },
    },
  },
  {
    id: "risk.supply.halt",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.55 },
    headlines: ["{name}, 핵심 부품 공급 차질… {product} 출하 {duration} 지연", "{country} 협력사 파업에 {name} 생산 차질"],
    excludeSectors: ["BROKER", "REIT"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      duration: { kind: "duration", range: { min: 2, max: 8 }, unit: "개월" },
      country: { kind: "pick", vocab: "country" },
    },
  },
  {
    id: "risk.cleared",
    category: "RISK",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{agency}, {name} 조사 '무혐의' 종결", "{name}, {agency} 제재 심의서 '경고'로 마무리… 불확실성 해소"],
    slots: { agency: { kind: "pick", vocab: "agency" } },
  },
];
