import type { NewsTemplate } from "../types";

/**
 * 산업군 — no company is named. `sectorExposure` decides which listings move and which
 * way: 1 is the industry the story is about, a smaller weight a knock-on, a negative
 * weight an industry the same news hurts. Built in up/down pairs so the pool itself
 * carries no drift (the picker does not filter sector stories by sentiment).
 */
export const SECTOR_TEMPLATES: readonly NewsTemplate[] = [
  // ── IT·반도체 ──────────────────────────────────────────────
  {
    id: "sec.semi.export.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: [
      "{quarter} 반도체 수출 {pct} 증가… 업황 회복 본격화",
      "반도체 수출 {pct} 늘며 {count} 연속 증가세",
    ],
    sectorExposure: { SEMICONDUCTOR: 1, ELECTRONICS: 0.55 },
    slots: {
      quarter: { kind: "quarter" },
      pct: { kind: "percent", range: { min: 8, max: 35 } },
      count: { kind: "count", range: { min: 3, max: 14 }, unit: "개월" },
    },
  },
  {
    id: "sec.semi.export.down",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: [
      "반도체 수출 {pct} 감소… 재고 조정 장기화 우려",
      "{quarter} 반도체 수출 {pct} 줄어… 메모리 가격 약세 지속",
    ],
    sectorExposure: { SEMICONDUCTOR: 1, ELECTRONICS: 0.55 },
    slots: {
      quarter: { kind: "quarter" },
      pct: { kind: "percent", range: { min: 5, max: 25 } },
    },
  },
  {
    id: "sec.memory.price.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.55 },
    headlines: ["D램 고정거래가격 {pct} 상승… 메모리 업황 반등 신호"],
    sectorExposure: { SEMICONDUCTOR: 1, ELECTRONICS: 0.4 },
    slots: { pct: { kind: "percent", range: { min: 5, max: 22 } } },
  },
  {
    id: "sec.chip.export.control",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: [
      "미국, 반도체 장비·기술 수출 통제 강화… 국내 업계 긴장",
      "미국 첨단 반도체 규제 확대… 중국 현지 공장 운영 차질 우려",
    ],
    sectorExposure: { SEMICONDUCTOR: 1, ELECTRONICS: 0.5 },
  },
  {
    id: "sec.ai.capex",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["글로벌 빅테크, AI 데이터센터 투자 {money} 확대 발표"],
    body: ["반도체·전력 설비·통신망 수요가 함께 늘어날 것이라는 전망이 나온다."],
    sectorExposure: { SEMICONDUCTOR: 1, ELECTRONICS: 0.4, UTILITY: 0.3, TELECOM: 0.3 },
    slots: { money: { kind: "macroMoney", eok: { min: 500_000, max: 3_000_000 } } },
  },
  {
    id: "sec.smartphone.weak",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["글로벌 스마트폰 출하량 {pct} 감소… 부품 수요 둔화 우려"],
    sectorExposure: { ELECTRONICS: 1, SEMICONDUCTOR: 0.45 },
    slots: { pct: { kind: "percent", range: { min: 4, max: 15 } } },
  },

  // ── 2차전지·소재 ────────────────────────────────────────────
  {
    id: "sec.ev.subsidy.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["{region}, 전기차 구매 보조금 확대… 배터리 수요 회복 기대"],
    sectorExposure: { BATTERY: 1, AUTO: 0.45, MATERIALS: 0.35 },
    slots: { region: { kind: "pick", vocab: "region" } },
  },
  {
    id: "sec.ev.demand.slow",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: [
      "전기차 판매 증가율 {pct}로 둔화… 수요 정체 장기화 우려",
      "{region} 전기차 보조금 조기 종료… 배터리 업계 비상",
    ],
    sectorExposure: { BATTERY: 1, AUTO: 0.4, MATERIALS: 0.35 },
    slots: {
      pct: { kind: "percent", range: { min: 2, max: 9 } },
      region: { kind: "pick", vocab: "region" },
    },
  },
  {
    id: "sec.lithium.drop",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["리튬 가격 {pct} 급락… 배터리 셀 원가 부담 완화"],
    body: ["원료를 파는 소재 업체에는 판가 하락 부담으로 작용한다."],
    sectorExposure: { BATTERY: 1, MATERIALS: -0.6 },
    slots: { pct: { kind: "percent", range: { min: 10, max: 30 } } },
  },
  {
    id: "sec.lithium.spike",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["리튬 가격 {pct} 급등… 배터리 셀 업체 원가 부담 확대"],
    body: ["원료 판가에 연동된 소재 업체는 수혜가 예상된다."],
    sectorExposure: { BATTERY: 1, MATERIALS: -0.6 },
    slots: { pct: { kind: "percent", range: { min: 10, max: 35 } } },
  },
  {
    id: "sec.chem.spread.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["석유화학 스프레드 {pct} 개선… 업황 바닥 통과 기대"],
    sectorExposure: { MATERIALS: 1, ENERGY: 0.3 },
    slots: { pct: { kind: "percent", range: { min: 8, max: 25 } } },
  },
  {
    id: "sec.chem.oversupply",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{region}발 석유화학 공급과잉 심화… 국내 설비 가동률 하향"],
    sectorExposure: { MATERIALS: 1, ENERGY: 0.3 },
    slots: { region: { kind: "pick", vocab: "region" } },
  },

  // ── 산업재 ─────────────────────────────────────────────────
  {
    id: "sec.ship.orders.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: [
      "글로벌 선박 발주 {pct} 증가… 신조선가 사상 최고",
      "LNG선 발주 러시… 조선업계 {count} 치 일감 확보",
    ],
    sectorExposure: { HEAVY: 1, TRADING: 0.25 },
    slots: {
      pct: { kind: "percent", range: { min: 10, max: 40 } },
      count: { kind: "count", range: { min: 3, max: 4 }, unit: "년" },
    },
  },
  {
    id: "sec.ship.orders.down",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["글로벌 선박 발주량 {pct} 급감… 조선업계 수주 공백 우려"],
    sectorExposure: { HEAVY: 1, TRADING: 0.25 },
    slots: { pct: { kind: "percent", range: { min: 15, max: 45 } } },
  },
  {
    id: "sec.construction.soc",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["정부, SOC 예산 {money} 증액… 건설 수주 확대 기대"],
    sectorExposure: { CONSTRUCTION: 1, HEAVY: 0.3, MATERIALS: 0.2 },
    slots: { money: { kind: "macroMoney", eok: { min: 20_000, max: 120_000 } } },
  },
  {
    id: "sec.construction.pf",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.4, max: 0.65 },
    headlines: [
      "부동산 PF 부실 우려 재점화… 건설사 유동성 점검 착수",
      "PF 대출 연체율 {pct}로 급등… 건설·금융권 긴장",
    ],
    sectorExposure: { CONSTRUCTION: 1, BROKER: 0.5, REIT: 0.35 },
    slots: { pct: { kind: "percent", range: { min: 3, max: 9 } } },
  },
  {
    id: "sec.housing.deregulate",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.33, max: 0.55 },
    headlines: [
      "정부, 재건축 규제 대폭 완화… 주택 공급 속도 낸다",
      "수도권 주택 {count} 공급 대책 발표… 건설업계 '환영'",
    ],
    sectorExposure: { CONSTRUCTION: 1, REIT: 0.4 },
    slots: { count: { kind: "count", range: { min: 50_000, max: 300_000 }, unit: "가구" } },
  },
  {
    id: "sec.housing.unsold",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.33, max: 0.55 },
    headlines: ["전국 미분양 주택 {count} 돌파… 10년 만에 최대"],
    sectorExposure: { CONSTRUCTION: 1, REIT: 0.3 },
    slots: { count: { kind: "count", range: { min: 70_000, max: 110_000 }, unit: "가구" } },
  },
  {
    id: "sec.trade.volume.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.28, max: 0.5 },
    headlines: ["{region} 교역량 회복… 수출입 물동량 {pct} 증가"],
    sectorExposure: { TRADING: 1, HEAVY: 0.3, AIRLINE: 0.3 },
    slots: {
      region: { kind: "pick", vocab: "region" },
      pct: { kind: "percent", range: { min: 5, max: 18 } },
    },
  },
  {
    id: "sec.trade.volume.down",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.28, max: 0.5 },
    headlines: ["글로벌 교역량 {pct} 감소… 무역·물류 업계 둔화 우려"],
    sectorExposure: { TRADING: 1, HEAVY: 0.3, AIRLINE: 0.3 },
    slots: { pct: { kind: "percent", range: { min: 3, max: 12 } } },
  },

  // ── 모빌리티 ───────────────────────────────────────────────
  {
    id: "sec.auto.sales.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.55 },
    headlines: ["{region} 자동차 판매 {pct} 증가… 한국차 점유율 역대 최고"],
    sectorExposure: { AUTO: 1, BATTERY: 0.3 },
    slots: {
      region: { kind: "pick", vocab: "region" },
      pct: { kind: "percent", range: { min: 5, max: 20 } },
    },
  },
  {
    id: "sec.auto.tariff",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.38, max: 0.62 },
    headlines: ["{region}, 수입 자동차 관세 {pct} 부과 검토… 완성차 업계 비상"],
    sectorExposure: { AUTO: 1, BATTERY: 0.35, MATERIALS: 0.2 },
    slots: {
      region: { kind: "pick", vocab: "region" },
      pct: { kind: "percent", range: { min: 10, max: 25 }, decimals: 0 },
    },
  },
  {
    id: "sec.travel.demand",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: [
      "해외여행 수요 급증… 국제선 여객 {pct} 증가",
      "연휴 앞두고 항공권 예약 {pct} 늘어… 역대 최대",
    ],
    sectorExposure: { AIRLINE: 1, ENTERTAINMENT: 0.2 },
    slots: { pct: { kind: "percent", range: { min: 10, max: 35 } } },
  },
  {
    id: "sec.air.safety",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["국토부, 항공 안전 규제 강화… 저비용 노선 운항 축소 불가피"],
    sectorExposure: { AIRLINE: 1 },
  },
  {
    id: "sec.auto.chip.shortage",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["차량용 반도체 공급 부족 재발… 완성차 {count} 감산 전망"],
    sectorExposure: { AUTO: 1, BATTERY: 0.2 },
    slots: { count: { kind: "count", range: { min: 50_000, max: 400_000 }, unit: "대" } },
  },
  {
    id: "sec.auto.fta",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["{region}{과} 자동차 관세 인하 합의… 완성차·부품 수출 탄력"],
    sectorExposure: { AUTO: 1, BATTERY: 0.25 },
    slots: { region: { kind: "pick", vocab: "region" } },
  },

  // ── 미디어·통신 ─────────────────────────────────────────────
  {
    id: "sec.game.license",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.55 },
    headlines: ["중국, 한국 게임 {count} 판호 무더기 발급"],
    sectorExposure: { GAME: 1, ENTERTAINMENT: 0.3 },
    slots: { count: { kind: "count", range: { min: 5, max: 18 }, unit: "종" } },
  },
  {
    id: "sec.game.regulation",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["확률형 아이템 규제 강화 법안 통과… 게임업계 매출 타격 우려"],
    sectorExposure: { GAME: 1 },
  },
  {
    id: "sec.kcontent.export",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["K-콘텐츠 수출 {pct} 증가… 글로벌 팬덤 확대"],
    sectorExposure: { ENTERTAINMENT: 1, GAME: 0.4, FOOD: 0.15, TELECOM: 0.15 },
    slots: { pct: { kind: "percent", range: { min: 8, max: 30 } } },
  },
  {
    id: "sec.hallyu.ban",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["중국, 한국 콘텐츠 유통 제한 재개 움직임… 엔터·게임주 긴장"],
    sectorExposure: { ENTERTAINMENT: 1, GAME: 0.45, FOOD: 0.2 },
  },
  {
    id: "sec.telecom.tariff.cut",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["정부, 통신비 인하 압박… 5G 요금제 전면 개편 요구"],
    sectorExposure: { TELECOM: 1 },
  },
  {
    id: "sec.telecom.spectrum",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["주파수 재할당 대가 {pct} 인하 확정… 통신사 비용 부담 완화"],
    sectorExposure: { TELECOM: 1 },
    slots: { pct: { kind: "percent", range: { min: 10, max: 30 } } },
  },

  // ── 헬스케어 ───────────────────────────────────────────────
  {
    id: "sec.bio.fast.review",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.55 },
    headlines: ["미국 규제당국, 신약 심사 기간 대폭 단축… 바이오 투자심리 개선"],
    sectorExposure: { BIO: 1 },
  },
  {
    id: "sec.bio.drug.price",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["미국, 약가 인하 행정명령 서명… 제약·바이오 수익성 우려"],
    sectorExposure: { BIO: 1 },
  },
  {
    id: "sec.bio.licensing.boom",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["올해 바이오 기술수출 {money} 돌파… 역대 최대"],
    sectorExposure: { BIO: 1 },
    slots: { money: { kind: "macroMoney", eok: { min: 80_000, max: 200_000 } } },
  },
  {
    id: "sec.bio.funding.freeze",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["바이오 벤처 투자 {pct} 급감… 자금난 경고등"],
    sectorExposure: { BIO: 1 },
    slots: { pct: { kind: "percent", range: { min: 20, max: 45 } } },
  },

  // ── 소비재 ─────────────────────────────────────────────────
  {
    id: "sec.food.price.hike",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["식품업계 가격 인상 잇따라… 수익성 개선 기대"],
    sectorExposure: { FOOD: 1 },
  },
  {
    id: "sec.food.grain.spike",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.5 },
    headlines: ["국제 곡물가 {pct} 급등… 식품업계 원가 부담 가중"],
    body: ["곡물을 들여오는 종합상사에는 트레이딩 수익 확대 요인이다."],
    sectorExposure: { FOOD: 1, TRADING: -0.35 },
    slots: { pct: { kind: "percent", range: { min: 8, max: 25 } } },
  },
  {
    id: "sec.consumer.sentiment.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["소비자심리지수 {level} 기록… 내수 회복 신호"],
    sectorExposure: { FOOD: 1, ENTERTAINMENT: 0.3, AIRLINE: 0.3, AUTO: 0.2 },
    slots: { level: { kind: "level", range: { min: 104, max: 112 }, unit: "", decimals: 1 } },
  },
  {
    id: "sec.consumer.retail.down",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.28, max: 0.48 },
    headlines: ["소매판매 {pct} 감소… 내수 부진 장기화"],
    sectorExposure: { FOOD: 1, ENTERTAINMENT: 0.3, AIRLINE: 0.3, AUTO: 0.2 },
    slots: { pct: { kind: "percent", range: { min: 1, max: 4 } } },
  },

  // ── 에너지·유틸리티 ─────────────────────────────────────────
  {
    id: "sec.refining.margin.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["정제마진 배럴당 {level} 회복… 정유업계 실적 개선 기대"],
    sectorExposure: { ENERGY: 1, MATERIALS: 0.25, AIRLINE: -0.2 },
    slots: { level: { kind: "level", range: { min: 8, max: 16 }, unit: "달러", decimals: 1 } },
  },
  {
    id: "sec.refining.margin.down",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["정제마진 배럴당 {level}{로} 추락… 정유사 적자 우려"],
    sectorExposure: { ENERGY: 1, MATERIALS: 0.25 },
    slots: { level: { kind: "level", range: { min: 1, max: 4 }, unit: "달러", decimals: 1 } },
  },
  {
    id: "sec.power.tariff.up",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.35, max: 0.6 },
    headlines: ["정부, 전기요금 kWh당 {level} 인상 확정… 전력사 적자 해소 기대"],
    body: ["전기를 많이 쓰는 화학·반도체 업계에는 비용 부담이 늘어난다."],
    sectorExposure: { UTILITY: 1, MATERIALS: -0.3, SEMICONDUCTOR: -0.2 },
    slots: { level: { kind: "level", range: { min: 5, max: 15 }, unit: "원", decimals: 1 } },
  },
  {
    id: "sec.power.tariff.freeze",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.35, max: 0.58 },
    headlines: ["전기요금 {quarter} 동결… 전력사 적자 누적 우려"],
    sectorExposure: { UTILITY: 1 },
    slots: { quarter: { kind: "quarter", offsetQuarters: 1 } },
  },
  {
    id: "sec.nuclear.expand",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.33, max: 0.55 },
    headlines: ["정부, 원전 {count} 신규 건설 추진… 전력 수급 안정 기대"],
    sectorExposure: { UTILITY: 1, HEAVY: 0.5, CONSTRUCTION: 0.3 },
    slots: { count: { kind: "count", range: { min: 2, max: 6 }, unit: "기" } },
  },
  {
    id: "sec.renewable.cut",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["재생에너지 보조금 {pct} 축소… 발전 투자 계획 차질"],
    sectorExposure: { UTILITY: 1, HEAVY: 0.3 },
    slots: { pct: { kind: "percent", range: { min: 15, max: 40 } } },
  },
  {
    id: "sec.oil.refinery.outage",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{region} 대형 정유시설 가동 중단… 아시아 정제마진 급등"],
    sectorExposure: { ENERGY: 1, AIRLINE: -0.25 },
    slots: { region: { kind: "pick", vocab: "region" } },
  },
  {
    id: "sec.oil.windfall.tax",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.33, max: 0.55 },
    headlines: ["정유사 횡재세 도입 논의 본격화… 업계 '이중 과세' 반발"],
    sectorExposure: { ENERGY: 1 },
  },

  // ── 금융·부동산 ─────────────────────────────────────────────
  {
    id: "sec.turnover.record",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["증시 일평균 거래대금 {money} 돌파… 증권업 실적 기대"],
    sectorExposure: { BROKER: 1 },
    slots: { money: { kind: "macroMoney", eok: { min: 200_000, max: 450_000 } } },
  },
  {
    id: "sec.broker.provision",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["금융당국, 증권사 PF 충당금 기준 강화… {money} 추가 적립 불가피"],
    sectorExposure: { BROKER: 1, CONSTRUCTION: 0.3, REIT: 0.3 },
    slots: { money: { kind: "macroMoney", eok: { min: 5_000, max: 30_000 } } },
  },
  {
    id: "sec.reit.tax",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["리츠 배당소득 분리과세 도입 확정… 투자 매력 부각"],
    sectorExposure: { REIT: 1, BROKER: 0.2 },
  },
  {
    id: "sec.office.vacancy",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["서울 오피스 공실률 {pct}로 상승… 임대료 하락 압력"],
    sectorExposure: { REIT: 1, CONSTRUCTION: 0.3 },
    slots: { pct: { kind: "percent", range: { min: 6, max: 12 } } },
  },
  {
    id: "sec.valueup.finance",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "POSITIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["밸류업 세제 혜택 확정… 저PBR 금융·배당주 재조명"],
    sectorExposure: { BROKER: 1, REIT: 0.45, UTILITY: 0.3, TELECOM: 0.2 },
  },
  {
    id: "sec.capital.gains.tax",
    category: "SECTOR",
    scope: "SECTOR",
    sentiment: "NEGATIVE",
    strength: { min: 0.3, max: 0.52 },
    headlines: ["대주주 양도세 기준 강화 추진… 연말 매도 물량 우려"],
    sectorExposure: { BROKER: 1 },
  },
];
