import type { NewsTemplate } from "../types";

/**
 * 후속 보도 — reachable only as a follow-up.
 *
 * These declare the same slot keys as their parent so the sequel inherits its
 * figures and reads as the same story rather than a new one. None of them
 * declares a `followUp` of its own: chain depth is capped at one so a story
 * can never spiral.
 */
export const SEQUEL_TEMPLATES: readonly NewsTemplate[] = [
  {
    id: "seq.order.contract",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.28, max: 0.5 },
    headlines: ["{name}, {country} {counterparty}{과} {money} {product} 본계약 체결"],
    slots: {
      country: { kind: "pick", vocab: "country" },
      counterparty: { kind: "pick", vocab: "counterparty" },
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.03, max: 0.22 } },
    },
  },
  {
    id: "seq.order.delay",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{name} {money} {product} 수주, 발주처 사정으로 착공 {duration} 연기"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.03, max: 0.22 } },
      duration: { kind: "duration", range: { min: 3, max: 18 }, unit: "개월" },
    },
  },
  {
    id: "seq.order.cancel",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.55, max: 0.85 },
    headlines: ["{name} {money} {product} 계약, 발주처 자금난에 해지"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.03, max: 0.22 } },
    },
  },
  {
    id: "seq.rights.priced",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.3, max: 0.55 },
    headlines: ["{name} 유상증자 발행가 {target}으로 확정… 현 주가 대비 {pct} 할인"],
    slots: {
      target: { kind: "targetPrice", ratio: { min: 0.68, max: 0.85 } },
      pct: { kind: "percent", range: { min: 15, max: 32 }, decimals: 0 },
    },
  },
  {
    id: "seq.rights.withdraw",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.45, max: 0.7 },
    headlines: ["{name}, {money} 유상증자 철회… 자체 조달로 선회"],
    slots: { money: { kind: "money", capFraction: { min: 0.08, max: 0.25 } } },
  },
  {
    id: "seq.rights.subscribed",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.28, max: 0.48 },
    headlines: ["{name} 유상증자 청약 경쟁률 {multiple}대 1… 실권주 없어"],
    slots: { multiple: { kind: "multiple", range: { min: 1.2, max: 8 }, decimals: 1 } },
  },
  {
    id: "seq.earn.upgrade_wave",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.25, max: 0.45 },
    headlines: ["{quarter} 실적 발표 후 {name} 목표주가 줄상향… {count} 증권사 눈높이 올려"],
    slots: {
      quarter: { kind: "quarter" },
      count: { kind: "count", range: { min: 3, max: 12 }, unit: "곳" },
    },
  },
  {
    id: "seq.earn.downgrade_wave",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.25, max: 0.45 },
    headlines: ["{name} 목표주가 줄하향… {count} 증권사가 눈높이 낮춰"],
    slots: { count: { kind: "count", range: { min: 3, max: 12 }, unit: "곳" } },
  },
  {
    id: "seq.legal.settle",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.3, max: 0.55 },
    headlines: ["{name}, {money} 소송 조정 합의… 부담액 {money2}로 축소"],
    slots: {
      money: { kind: "money", capFraction: { min: 0.005, max: 0.04 } },
      money2: { kind: "money", capFraction: { min: 0.001, max: 0.01 } },
    },
  },
  {
    id: "seq.legal.expand",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.35, max: 0.6 },
    headlines: ["{name} 소송전 확대… {country}서도 동일 소송 제기"],
    slots: { country: { kind: "pick", vocab: "country" } },
  },
  {
    id: "seq.embezzle.indict",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.6, max: 0.9 },
    headlines: ["검찰, {name} {title} 구속기소… 경영 공백 장기화"],
    slots: { title: { kind: "pick", vocab: "title" } },
  },
  {
    id: "seq.embezzle.clear",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.55, max: 0.85 },
    headlines: ["{name} {title}, 혐의 무혐의 처분… 불확실성 해소"],
    slots: { title: { kind: "pick", vocab: "title" } },
  },
  {
    id: "seq.recall.expand",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.4, max: 0.65 },
    headlines: ["{name} {product} 리콜 확대… 대상 {count}{로} 늘어"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      count: { kind: "count", range: { min: 50_000, max: 900_000 }, unit: "개" },
    },
  },
  {
    id: "seq.recall.close",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.28, max: 0.5 },
    headlines: ["{name}, {product} 리콜 조치 완료… 비용 {money}에 그쳐"],
    slots: {
      product: { kind: "pick", vocab: "product" },
      money: { kind: "money", capFraction: { min: 0.001, max: 0.01 } },
    },
  },
  {
    id: "seq.ma.confirm",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "POSITIVE",
    sequelOnly: true,
    strength: { min: 0.45, max: 0.75 },
    headlines: ["{name} 경영권 매각 협상 공식화… 실사 착수"],
  },
  {
    id: "seq.ma.deny",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.5, max: 0.8 },
    headlines: ['{name} "매각설 사실무근" 공시… 급등분 되돌림'],
  },
  {
    id: "seq.squeeze.fade",
    category: "SEQUEL",
    scope: "SYMBOL",
    sentiment: "NEGATIVE",
    sequelOnly: true,
    strength: { min: 0.3, max: 0.5 },
    headlines: ["{name} 숏커버 일단락… 차익 실현 매물 출회"],
  },
];
